source_directories:
    - /mnt/source/
repositories:
    - path: /mnt/borg-repository
      label: local
    - path: ssh://borg@home.rikvoorhaar.com/home/borg/backups
      label: remote
one_file_system: true

compression: lz4
archive_name_format: 'backup-{now}'

keep_hourly: 2
keep_daily: 7
keep_weekly: 4
keep_monthly: 12
keep_yearly: 10

retries: 3
retry_wait: 10

checks:
  - name: repository
    frequency: 2 weeks
  - name: archives
    frequency: always
  - name: extract
    frequency: 2 weeks
  - name: data
    frequency: 1 month

before_backup:
    - echo "Starting a backup job."
after_backup:
    - echo "Backup created."
on_error:
    - echo "Error while creating a backup."

before_everything:
    - echo "Borg is staring."
after_everything:
    - echo "All backups done."

healthchecks:
    ping_url: ${BORG_HEALTHCHECK_URL}