networks:
  loki:

services:
  loki:
    image: grafana/loki:2.9.2
    # ports:
    #   - "3100:3100"
    command: -config.file=/etc/loki/config/loki.yml
    networks:
      - loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`loki.rikvoorhaar.com`)"
      - "traefik.http.routers.loki.entrypoints=websecure"
      - "traefik.http.routers.loki.tls=true"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
    volumes:
      - ./config/loki.yml:/etc/loki/config/loki.yml
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - /var/log:/var/log
      - ./config/promtail.yml:/etc/promtail/config/promtail.yml
    command: -config.file=/etc/promtail/config/promtail.yml
    networks:
      - loki
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"

  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_PATHS_CONFIG=/etc/grafana/config/grafana.ini
      # - GF_AUTH_ANONYMOUS_ENABLED=true
      # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: https://loki.rikvoorhaar.com
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:latest
    # ports:
    #   - "3000:3000"
    volumes:
      - "./grafana-data/:/var/lib/grafana"
      - "./config/grafana.ini:/etc/grafana/config/grafana.ini"
    networks:
      - loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`grafana.rikvoorhaar.com`)"
      - "traefik.http.routers.grafana.entrypoints=websecure"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
    logging:
      driver: loki
      options:
        loki-url: "http://loki:3100/loki/api/v1/push"
