services:
    reverse-proxy:
        image: traefik:latest
        network_mode: "host"
        restart: always
        command:
            - "--api=true"
            - "--providers.docker=true"
            - "--entrypoints.web.address=:80"
            - "--entrypoints.web.address=:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "./traefik.yml:/etc/traefik/traefik.yml"
            - "./conf:/etc/traefik/conf/"
            - "./acme.json:/etc/traefik/acme.json"
    dashboard:
        image: traefik:latest
        command:
            - "--api=true"
        labels:
            - "traefik.enable=True"
            - "traefik.http.routers.api.rule=Host(`traefik2.rikvoorhaar.com`)"
            - "traefik.http.routers.api.entrypoints=websecure"
            - "traefik.http.routers.api.tls=true"
            - "traefik.http.routers.api.tls.certresolver=myresolver"
            - "traefik.http.routers.api.service=api@internal"
            - "traefik.http.routers.api.middlewares=auth"
            - "traefik.http.middlewares.auth.basicauth.users=rik:${TRAEFIK_BASIC_AUTH}"