entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: rik.voorhaar@gmail.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web


api:
    dashboard: true

providers:
    docker: {}
