entryPoints:
    web:
        address: ":80"

    websecure:
        address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: rik.voorhaar@gmail.com
      storage: /letsencrypt/acme.json
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      httpChallenge:
        # used during the challenge
        entryPoint: web


api:
    dashboard: true

providers:
  docker: {}
  file:
    directory: "/etc/traefik/conf/" # Adjust the path according your needs.
    watch: true