services:
  external:
    container_name: blog
    image: ghcr.io/RikVoorhaar/blog:latest
    user: "node"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blog.rule=Host(`blog.rikvoorhaar.com`) || Host(`www.rikvoorhaar.com`) || Host(`rikvoorhaar.com`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls=true"
      - "traefik.http.services.blog.loadbalancer.server.port=3000"
    networks:
      - internal

networks:
  internal:
  web:
    external: true
