services:
  db:
    image: mariadb:10.11
    command: --max-allowed-packet=64MB
    restart: always
    volumes:
      - ./db.d:/var/lib/mysql
    env_file:
      - ./db.env
    networks:
      - internal

  app:
    image: matomo:fpm-alpine
    restart: always
    volumes:
      - ./matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=db
      - PHP_MEMORY_LIMIT=2048M
    env_file:
      - ./db.env
    networks:
      - internal

  web:
    image: nginx:alpine
    restart: always
    volumes:
      - ./matomo:/var/www/html
      - ./matomo.conf:/etc/nginx/conf.d/default.conf
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.matomo.rule=Host(`matomo.rikvoorhaar.com`)"
      - "traefik.http.routers.matomo.entrypoints=websecure"
      - "traefik.http.routers.matomo.tls=true"
      - "traefik.http.routers.matomo.tls.certresolver=myresolver"
      - "traefik.http.services.matomo.loadbalancer.server.port=80"
    networks:
      - internal

networks:
  internal:
  web:
    external: true

